name: Build and Release AnymeX

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"

      - name: Setup .env File
        env:
          AL_CLIENT_ID: ${{ secrets.AL_CLIENT_ID }}
          AL_CLIENT_SECRET: ${{ secrets.AL_CLIENT_SECRET }}
          SIMKL_CLIENT_ID: ${{ secrets.SIMKL_CLIENT_ID }}
          SIMKL_CLIENT_SECRET: ${{ secrets.SIMKL_CLIENT_SECRET }}
          MAL_CLIENT_ID: ${{ secrets.MAL_CLIENT_ID }}
          MAL_CLIENT_SECRET: ${{ secrets.MAL_CLIENT_SECRET }}
          CALLBACK_SCHEME: ${{ secrets.CALLBACK_SCHEME }}
        run: |
          echo "AL_CLIENT_ID=$AL_CLIENT_ID" > .env
          echo "AL_CLIENT_SECRET=$AL_CLIENT_SECRET" >> .env
          echo "SIMKL_CLIENT_ID=$SIMKL_CLIENT_ID" >> .env
          echo "SIMKL_CLIENT_SECRET=$SIMKL_CLIENT_SECRET" >> .env
          echo "MAL_CLIENT_ID=$MAL_CLIENT_ID" >> .env
          echo "MAL_CLIENT_SECRET=$MAL_CLIENT_SECRET" >> .env
          echo "CALLBACK_SCHEME=$CALLBACK_SCHEME" >> .env

      - name: Get Dependencies
        run: flutter pub get

      - name: Setup Signing Files
        env:
          P12_BASE64: ${{ secrets.P12_CERTIFICATE }}
          PROVISIONING_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE }}
        run: |
          echo "$P12_BASE64" | base64 -d > certificate.p12
          echo "$PROVISIONING_PROFILE_BASE64" | base64 -d > profile.mobileprovision
          chmod +x ./scripts/sign-ipa.sh

      - name: Build iOS
        env:
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir -p Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r AnymeX-iOS-${{ github.ref_name }}-unsigned.ipa Payload
          cd ../../../
          ./scripts/sign-ipa.sh build/ios/iphoneos/AnymeX-iOS-${{ github.ref_name }}-unsigned.ipa ./certificate.p12 "$P12_PASSWORD" ./profile.mobileprovision ./AnymeX-iOS-${{ github.ref_name }}.ipa
        continue-on-error: true

      - name: Handle iOS Signing Failure
        if: steps.sign-ipa.outcome != 'success'
        run: |
          echo "IPA signing failed, taking alternative action..."
          mv "build/ios/iphoneos/AnymeX-iOS-${{ github.ref_name }}-unsigned.ipa" "AnymeX-iOS-${{ github.ref_name }}.ipa"

      - name: Release iOS IPA
        uses: ncipollo/release-action@v1
        with:
          artifacts: "AnymeX-iOS-${{ github.ref_name }}.ipa"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          tag: ${{ github.ref_name }}

  call-workflow-sideloading:
    needs: build-ios
    uses: ./.github/workflows/update_sideloading_source.yml